apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-mongo-pv
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/auth-mongo
